export const itemsArr = [
  {
    id: 1,
    name: 'Sony - WH-1000XM5 Wireless ',
    rating: 5,
    category: 'Noise Canceling',
    price: 299.99,
    image: '/imgBest Seller/pirmaAusine.png',
  },
  {
    id: 2,
    name: 'Beats Studio Pro',
    rating: 5,
    category: 'Noise Canceling',
    price: 349.99,
    image: '/imgBest Seller/antraAusine.png',
  },
  {
    id: 3,
    name: 'Sony - WH-CH720N Wireless',
    rating: 5,
    category: 'Noise Canceling',
    price: 149.99,
    image: '/imgBest Seller/treciaAusine.png',
  },
  {
    id: 4,
    name: 'Skullcandy - Rail True Wireless ',
    rating: 5,
    category: 'Earbuds',
    price: 79.99,
    image: '/imgBest Seller/ketvirtaAusine.png',
  },
  {
    id: 5,
    name: 'Beats Studio Pro',
    rating: 5,
    category: 'Earbuds',
    price: 249.99,
    image: '/imgBest Seller/penktaAusine.png',
  },
  {
    id: 6,
    name: 'JBL Reflect Flow Pro+ Bluetooth',
    rating: 5,
    category: 'Truly Wireless Sports',
    price: 179.95,
    image: '/imgBest Seller/sestaAusine.png',
  },
  {
    id: 7,
    name: 'Bose QuietComfort Headphones',
    rating: 5,
    category: 'Noise Canceling',
    price: 349.0,
    image: '/imgBest Seller/septintaAusine.png',
  },
  {
    id: 8,
    name: 'AKG Y600NC Wireless',
    rating: 5,
    category: 'Noise Canceling',
    price: 349.99,
    image: '/imgBest Seller/astuntaAusine.png',
  },
];
